#!/bin/bash

# Integration tests for the test-migration feature (signature projection,
# snapshot store, pin, stub synthesis, and `migrate status` / `init` / `diff`).
# Pure logic (canonical projection + drift invariants, the textual parser, the
# bucketing decision table) is unit-tested in test-case-parser/test/test.ml;
# this script covers what needs the real compiler end-to-end.
#
# Fixtures: opttup.catala_en (OptTup.Calc) exercises option, tuple, nested
# struct/enum in I/O; test_opttup.catala_en holds rich values for them.

cd "$(dirname "$0")"

function cleanup(){
    rm -rf _build
    rm -rf _sig_stub
    rm -rf _sig_snap
    rm -rf _migrate
    rm -rf _init
    rm -rf _applyplan
    rm -rf _xform
}

trap cleanup EXIT

clerk start

sighash() { catala testcase sig-hash | cut -f2; }

# --- Representation-independence: list-scopes hash == test tested_scope hash -
# (closes the drift-detection loop: save-side and read-side must agree, against
# the REAL compiler output for both paths)
LS_HASH=$(catala testcase list-scopes opttup.catala_en | sighash)
TS_HASH=$(catala testcase read test_opttup.catala_en | jq -c '[.[0].tested_scope]' | sighash)
[ "$LS_HASH" = "$TS_HASH" ] || { echo "FAIL: list-scopes hash ($LS_HASH) != tested_scope hash ($TS_HASH)"; exit 1; }

# --- Stub synthesis value recovery (the migration sidestep) -----------------
# Read rich option/tuple values against the REAL module, then against ONLY a
# synthesized stub (real module absent). Both must recover identical values.
catala testcase read test_opttup.catala_en > _sig_real.json
mkdir -p _sig_stub
catala testcase list-scopes opttup.catala_en \
  | catala testcase stub --output-dir _sig_stub --language en
cp test_opttup.catala_en _sig_stub/
printf '[project]\ninclude_dirs = ["."]\n' > _sig_stub/clerk.toml
( cd _sig_stub && clerk start >/dev/null 2>&1 && catala testcase read test_opttup.catala_en ) > _sig_stub.json
diff <(jq -S . _sig_real.json) <(jq -S . _sig_stub.json) > /dev/null \
  || { echo "FAIL: stub-recovered values differ from real-module values"; exit 1; }
rm -f _sig_real.json _sig_stub.json

# Stub is SIGNATURE-ONLY: it recovers values, it does not compute. So it must
# carry the do-not-edit banner and emit NO output definitions (outputs left
# undefined on purpose). Calc has no context inputs, so there is no scope body
# at all here.
grep -q 'AUTOGENERATED MIGRATION STUB' _sig_stub/OptTup.catala_en \
  || { echo "FAIL: stub is missing its do-not-edit banner"; exit 1; }
grep -qE '^\s*definition (result|combo) ' _sig_stub/OptTup.catala_en \
  && { echo "FAIL: stub emitted an output definition (should be signature-only)"; exit 1; }
# Recovery must work AND typecheck against the signature-only stub.
( cd _sig_stub && clerk typecheck test_opttup.catala_en ) >/dev/null 2>&1 \
  || { echo "FAIL: test does not typecheck against the signature-only stub"; exit 1; }

# --- Stub + value round-trip must typecheck (tuples emitted as (a, b)) -------
# Also exercises the signature pin (#[testcase.sig]) + snapshot store (--sig-dir).
catala testcase read test_opttup.catala_en \
  | catala testcase write --language en --sig-dir _sig_snap > _sig_stub/test_opttup_rt.catala_en
grep -q 'definition calc.pair equals (7, $3.00)' _sig_stub/test_opttup_rt.catala_en \
  || { echo "FAIL: tuple value not emitted as (a, b)"; exit 1; }
( cd _sig_stub && clerk typecheck test_opttup_rt.catala_en ) || exit 1

# Pin is stamped on write and its hash matches the live (list-scopes) hash.
grep -q "#\[testcase.sig = \"OptTup.Calc@$LS_HASH\"\]" _sig_stub/test_opttup_rt.catala_en \
  || { echo "FAIL: signature pin not stamped as OptTup.Calc@$LS_HASH"; exit 1; }
# Pin round-trips back through read into the sig_pin field.
( cd _sig_stub && catala testcase read test_opttup_rt.catala_en ) \
  | jq -e --arg p "OptTup.Calc@$LS_HASH" '.[0].sig_pin == $p' > /dev/null \
  || { echo "FAIL: sig_pin not recovered on read"; exit 1; }
# Snapshot store: content-addressed scope_def JSON, named by the same hash.
[ -f "_sig_snap/OptTup.Calc@$LS_HASH.sig.json" ] \
  || { echo "FAIL: signature snapshot not written"; exit 1; }
jq -e '.name == "Calc" and .module_name == "OptTup"' "_sig_snap/OptTup.Calc@$LS_HASH.sig.json" > /dev/null \
  || { echo "FAIL: snapshot is not a valid scope_def for OptTup.Calc"; exit 1; }
# sig-hash accepts a single scope_def object (a snapshot file), not just a list,
# from stdin OR a filename argument.
[ "$(catala testcase sig-hash < "_sig_snap/OptTup.Calc@$LS_HASH.sig.json" | cut -f2)" = "$LS_HASH" ] \
  || { echo "FAIL: sig-hash on a single snapshot object (stdin) did not match LS_HASH"; exit 1; }
[ "$(catala testcase sig-hash "_sig_snap/OptTup.Calc@$LS_HASH.sig.json" | cut -f2)" = "$LS_HASH" ] \
  || { echo "FAIL: sig-hash on a single snapshot file (argument) did not match LS_HASH"; exit 1; }
# Content-addressed: a second write must not error and must not duplicate.
catala testcase read test_opttup.catala_en \
  | catala testcase write --language en --sig-dir _sig_snap > /dev/null
[ "$(ls _sig_snap | wc -l)" -eq 1 ] \
  || { echo "FAIL: snapshot store not content-addressed (expected 1 file)"; exit 1; }

# ============================================================================
# migrate status: drift triage into fresh / stale / unknown / blocked.
# Self-contained project in _migrate: a stub OptTup module + a pinned test +
# its committed snapshot, then we drift the module and re-triage.
# ============================================================================
rm -rf _migrate && mkdir -p _migrate
catala testcase list-scopes opttup.catala_en \
  | catala testcase stub --output-dir _migrate --language en
catala testcase read test_opttup.catala_en \
  | catala testcase write --language en --sig-dir _migrate > _migrate/t.catala_en
printf '[project]\ninclude_dirs = ["."]\n' > _migrate/clerk.toml
( cd _migrate && clerk start >/dev/null 2>&1 )

state() { # state() FILE -> prints the first entry's state
  ( cd _migrate && catala testcase migrate status --json "$1" 2>/dev/null ) | jq -r '.[0].state'
}

# fresh: pin == live
[ "$(state t.catala_en)" = "Fresh" ] \
  || { echo "FAIL(migrate): expected Fresh for pinned, undrifted test"; exit 1; }

# gate (Step 0): --check passes (exit 0) when nothing is stale/blocked
( cd _migrate && catala testcase migrate status --check t.catala_en >/dev/null 2>&1 ) \
  || { echo "FAIL(gate): --check must pass on a fresh suite"; exit 1; }

# unknown: a test with no #[testcase.sig] pin
grep -v 'testcase.sig' _migrate/t.catala_en > _migrate/u.catala_en
[ "$(state u.catala_en)" = "Unknown" ] \
  || { echo "FAIL(migrate): expected Unknown for unpinned test"; exit 1; }

# drift the live module: rename an input (changes the signature)
sed -i 's/input pair content/input pair2 content/' _migrate/OptTup.catala_en
( cd _migrate && clerk start >/dev/null 2>&1 )

# stale: pin != live, pinned snapshot still present -> migratable
[ "$(state t.catala_en)" = "Stale" ] \
  || { echo "FAIL(migrate): expected Stale after drift with snapshot present"; exit 1; }

# gate (Step 0): --check now fails (exit 1) because a test is stale
if ( cd _migrate && catala testcase migrate status --check t.catala_en >/dev/null 2>&1 ); then
  echo "FAIL(gate): --check must fail when a test is stale"; exit 1
fi

# migrate diff: the structured canonical diff of the snapshot vs live shows the
# input rename as a removed + added pair (input renames are not auto-grouped).
DIFF=$( cd _migrate && catala testcase migrate diff t.catala_en 2>/dev/null )
echo "$DIFF" | grep -q '^[[:space:]]*- input pair: tuple(int,money)$' \
  || { echo "FAIL(diff): expected '- input pair ...' line; got:"; echo "$DIFF"; exit 1; }
echo "$DIFF" | grep -q '^[[:space:]]*+ input pair2: tuple(int,money)$' \
  || { echo "FAIL(diff): expected '+ input pair2 ...' line; got:"; echo "$DIFF"; exit 1; }

# blocked: same drift but the pinned snapshot is gone -> not recoverable
mv _migrate/OptTup.Calc@*.sig.json _migrate/_hidden.sig.json
[ "$(state t.catala_en)" = "Blocked" ] \
  || { echo "FAIL(migrate): expected Blocked when snapshot is missing"; exit 1; }
mv _migrate/_hidden.sig.json _migrate/OptTup.Calc@"$LS_HASH".sig.json

# blocked (compile error): if the live module itself won't compile, status must
# report a clear reason and not crash.
cp _migrate/OptTup.catala_en _migrate/OptTup.bak
sed -i 's/  input items content list of optional of integer/  input items content list of optional of integer\n  input items content list of optional of integer/' _migrate/OptTup.catala_en
( cd _migrate && clerk start >/dev/null 2>&1 )
( cd _migrate && catala testcase migrate status t.catala_en 2>/dev/null ) | grep -qi 'does not compile' \
  || { echo "FAIL(migrate): expected a 'does not compile' blocked reason"; exit 1; }
mv _migrate/OptTup.bak _migrate/OptTup.catala_en
( cd _migrate && clerk start >/dev/null 2>&1 )

# directory mode: recurses, triages every test, skips the module file
DIR_STATES=$( ( cd _migrate && catala testcase migrate status --json . 2>/dev/null ) \
  | jq -r '[.[].state] | sort | join(",")' )
[ "$DIR_STATES" = "Stale,Unknown" ] \
  || { echo "FAIL(migrate): dir mode states = '$DIR_STATES' (expected Stale,Unknown)"; exit 1; }

# one-hash-per-scope: a second test of the same scope at a different pin is a
# half-migrated cluster ("split"). Throwaway file, removed right after.
cp _migrate/t.catala_en _migrate/tsplit.catala_en
sed -i 's/Calc_rich/Calc_split/; s/@[0-9a-f]\{32\}/@ffffffffffffffffffffffffffffffff/' _migrate/tsplit.catala_en
( cd _migrate && catala testcase migrate status . 2>/dev/null ) \
  | grep -qE '^  split +OptTup.Calc +2 distinct pins' \
  || { echo "FAIL(split): two pins for one scope not reported as split"; exit 1; }
rm -f _migrate/tsplit.catala_en

# ============================================================================
# migrate plan: emit the editable TOML worklist for the same `pair`->`pair2`
# drift, then track progress against it. The input rename is not auto-grouped,
# so the plan drops `pair` (auto) and lists `pair2` as a fill to resolve.
# ============================================================================
( cd _migrate && catala testcase migrate plan -o plan.toml t.catala_en 2>/dev/null )
PLAN=_migrate/plan.toml
[ -f "$PLAN" ] || { echo "FAIL(plan): plan file not written"; exit 1; }
grep -q 'path = "in.pair2"' "$PLAN" \
  || { echo "FAIL(plan): added input pair2 not listed as a fill; got:"; cat "$PLAN"; exit 1; }
grep -qE 'auto = \[.*drop in.pair' "$PLAN" \
  || { echo "FAIL(plan): dropped input pair not in the auto block; got:"; cat "$PLAN"; exit 1; }

# status --plan: the fill is pending; --check fails the gate while it is open.
( cd _migrate && catala testcase migrate status --plan plan.toml t.catala_en 2>/dev/null ) \
  | grep -qE 'fills +0/1' \
  || { echo "FAIL(plan): status --plan should show fills 0/1"; exit 1; }
if ( cd _migrate && catala testcase migrate status --check --plan plan.toml t.catala_en >/dev/null 2>&1 ); then
  echo "FAIL(plan): --check --plan should fail while a fill is pending"; exit 1
fi

# resolve the fill (give it a value) -> progress advances, the gate passes.
sed -i 's/  todo = true/  value = "(1, $2.00)"/' "$PLAN"
( cd _migrate && catala testcase migrate status --plan plan.toml t.catala_en 2>/dev/null ) \
  | grep -qE 'fills +1/1' \
  || { echo "FAIL(plan): status --plan should show fills 1/1 after editing"; exit 1; }
( cd _migrate && catala testcase migrate status --check --plan plan.toml t.catala_en >/dev/null 2>&1 ) \
  || { echo "FAIL(plan): --check --plan should pass once the fill is resolved"; exit 1; }
rm -f "$PLAN"

# ============================================================================
# migrate apply: recover -> rewrite -> write -> verify. The live drift here is
# `pair` (tuple input) renamed to `pair2`; input renames are not auto-grouped, so
# the old `pair` value is dropped and `pair2` is a NeedsValue hole left as
# `impossible`. The other recovered values must survive, and the result must be
# Fresh + read back against live.
# ----------------------------------------------------------------------------
# dry-run reports the hole and writes NOTHING.
BEFORE=$(md5sum _migrate/t.catala_en | cut -d' ' -f1)
DRY=$( cd _migrate && catala testcase migrate apply --dry-run t.catala_en 2>/dev/null )
echo "$DRY" | grep -qi 'NEEDS VALUE' \
  || { echo "FAIL(apply): dry-run should report a NEEDS VALUE hole; got:"; echo "$DRY"; exit 1; }
[ "$(md5sum _migrate/t.catala_en | cut -d' ' -f1)" = "$BEFORE" ] \
  || { echo "FAIL(apply): --dry-run modified the file"; exit 1; }

# real apply: rewrites, re-pins, marks the added input #[testcase.todo], verifies.
APPLY=$( cd _migrate && catala testcase migrate apply t.catala_en 2>/dev/null )
echo "$APPLY" | grep -qi 'verified against live' \
  || { echo "FAIL(apply): expected 'verified against live'; got:"; echo "$APPLY"; exit 1; }
# the added input (pair2) is written as an `impossible` hole carrying #[testcase.todo]
grep -qE 'pair2.*#\[testcase.todo\]|#\[testcase.todo\].*$' _migrate/t.catala_en \
  || { echo "FAIL(apply): #[testcase.todo] marker not written on the hole"; exit 1; }
grep -q 'definition .*pair2 ' _migrate/t.catala_en \
  || { echo "FAIL(apply): pair2 hole not written"; exit 1; }
# the marker round-trips through read into the value's attrs
( cd _migrate && catala testcase read t.catala_en 2>/dev/null ) \
  | jq -e '.[0].test_inputs.pair2.value.value.attrs | index("Todo")' >/dev/null \
  || { echo "FAIL(apply): #[testcase.todo] did not round-trip through read"; exit 1; }
# a recovered value survived the migration (maybe_amount was not touched)
grep -q 'definition calc.maybe_amount equals Present content' _migrate/t.catala_en \
  || { echo "FAIL(apply): a recovered value did not survive the migration"; exit 1; }
# and the migrated test is now Fresh against live
[ "$(state t.catala_en)" = "Fresh" ] \
  || { echo "FAIL(apply): migrated test is not Fresh"; exit 1; }

# NeedsDecision is a hard stop: a scalar retype must leave the test STALE
# (untouched), preserving the old value as the future transform's input.
cp _migrate/OptTup.catala_en _migrate/OptTup.dbak
sed -i 's/input maybe_amount content optional of money/input maybe_amount content optional of decimal/' _migrate/OptTup.catala_en
( cd _migrate && clerk start >/dev/null 2>&1 )
DEC=$( cd _migrate && catala testcase migrate apply t.catala_en 2>/dev/null )
echo "$DEC" | grep -qi 'left STALE' \
  || { echo "FAIL(apply): NeedsDecision must leave the test stale; got:"; echo "$DEC"; exit 1; }
mv _migrate/OptTup.dbak _migrate/OptTup.catala_en
( cd _migrate && clerk start >/dev/null 2>&1 )

# ============================================================================
# migrate init: seed pins onto unpinned tests that typecheck; refuse drifted.
# Own project (_init) so it doesn't perturb the status triage above.
# ============================================================================
rm -rf _init && mkdir -p _init
catala testcase list-scopes opttup.catala_en \
  | catala testcase stub --output-dir _init --language en
catala testcase read test_opttup.catala_en \
  | catala testcase write --language en > _init/s.catala_en
sed -i '/testcase.sig/d' _init/s.catala_en   # make it unpinned
printf '[project]\ninclude_dirs = ["."]\n' > _init/clerk.toml
( cd _init && clerk start >/dev/null 2>&1 )

# seed: unpinned + typechecks -> stamps the live pin and the snapshot
( cd _init && catala testcase migrate init s.catala_en >/dev/null 2>&1 )
grep -q "#\[testcase.sig = \"OptTup.Calc@$LS_HASH\"\]" _init/s.catala_en \
  || { echo "FAIL(init): pin not seeded into unpinned test"; exit 1; }
[ -f "_init/OptTup.Calc@$LS_HASH.sig.json" ] \
  || { echo "FAIL(init): snapshot not written by init"; exit 1; }
( cd _init && catala testcase migrate status s.catala_en 2>/dev/null ) | grep -q '^fresh:   1' \
  || { echo "FAIL(init): seeded test is not Fresh"; exit 1; }

# idempotent: re-running init on a now-pinned file adds no second pin
( cd _init && catala testcase migrate init s.catala_en >/dev/null 2>&1 )
[ "$(grep -c 'testcase.sig' _init/s.catala_en)" -eq 1 ] \
  || { echo "FAIL(init): re-init duplicated the pin"; exit 1; }

# refuse: an unpinned test that no longer typechecks (drift) is left untouched
catala testcase read test_opttup.catala_en \
  | catala testcase write --language en > _init/r.catala_en
sed -i '/testcase.sig/d' _init/r.catala_en
sed -i 's/input pair content/input pair2 content/' _init/OptTup.catala_en
( cd _init && clerk start >/dev/null 2>&1 )
( cd _init && catala testcase migrate init r.catala_en >/dev/null 2>&1 )
[ "$(grep -c 'testcase.sig' _init/r.catala_en)" -eq 0 ] \
  || { echo "FAIL(init): drifted unpinned test must be left untouched"; exit 1; }

# ============================================================================
# migrate apply --plan: consume the human's decisions. Own project (_applyplan)
# so it doesn't perturb the triage above. Drift = a new input (`rate`); the plan
# supplies its value, and apply --plan writes that value (not a #[testcase.todo]
# hole) and verifies. An ill-typed fill is refused (warned, left a hole).
# ============================================================================
rm -rf _applyplan && mkdir -p _applyplan
catala testcase list-scopes opttup.catala_en \
  | catala testcase stub --output-dir _applyplan --language en
catala testcase read test_opttup.catala_en \
  | catala testcase write --language en --sig-dir _applyplan > _applyplan/t.catala_en
printf '[project]\ninclude_dirs = ["."]\n' > _applyplan/clerk.toml
# drift: add an input `rate content decimal`
sed -i 's/\(input pair content (integer, money)\)/\1\n  input rate content decimal/' _applyplan/OptTup.catala_en
( cd _applyplan && clerk start >/dev/null 2>&1 )
[ "$( ( cd _applyplan && catala testcase migrate status --json t.catala_en 2>/dev/null ) | jq -r '.[0].state' )" = "Stale" ] \
  || { echo "FAIL(apply-plan): expected Stale after adding an input"; exit 1; }

# plan lists `rate` as a fill; fill it with a value, then apply --plan.
( cd _applyplan && catala testcase migrate plan -o plan.toml t.catala_en 2>/dev/null )
grep -q 'path = "in.rate"' _applyplan/plan.toml \
  || { echo "FAIL(apply-plan): rate not listed as a fill"; exit 1; }
sed -i 's/  todo = true/  value = "3.5"/' _applyplan/plan.toml
AP=$( cd _applyplan && catala testcase migrate apply --plan plan.toml t.catala_en 2>/dev/null )
echo "$AP" | grep -qiE '1 filled' \
  || { echo "FAIL(apply-plan): expected '1 filled'; got:"; echo "$AP"; exit 1; }
echo "$AP" | grep -qi 'verified against live' \
  || { echo "FAIL(apply-plan): result must verify against live; got:"; echo "$AP"; exit 1; }
grep -q 'definition .*rate equals 3.5' _applyplan/t.catala_en \
  || { echo "FAIL(apply-plan): filled value not written into the test"; exit 1; }
grep -q 'testcase.todo' _applyplan/t.catala_en \
  && { echo "FAIL(apply-plan): a filled slot must not keep a #[testcase.todo] marker"; exit 1; }
[ "$( ( cd _applyplan && catala testcase migrate status --json t.catala_en 2>/dev/null ) | jq -r '.[0].state' )" = "Fresh" ] \
  || { echo "FAIL(apply-plan): migrated test is not Fresh"; exit 1; }

# an ill-typed fill is refused: warn, write nothing, leave the hole.
catala testcase read test_opttup.catala_en \
  | catala testcase write --language en --sig-dir _applyplan > _applyplan/t.catala_en
( cd _applyplan && catala testcase migrate plan -o plan.toml t.catala_en 2>/dev/null )
sed -i 's/  todo = true/  value = "not a number"/' _applyplan/plan.toml
BAD=$( cd _applyplan && catala testcase migrate apply --dry-run --plan plan.toml t.catala_en 2>/dev/null )
echo "$BAD" | grep -qi 'did not parse' \
  || { echo "FAIL(apply-plan): ill-typed fill must be reported; got:"; echo "$BAD"; exit 1; }

# ============================================================================
# migrate apply --plan + TRANSFORM: a NeedsDecision (scalar retype) resolved by a
# Catala scope. Uses the REAL module (bodies, so it compiles to a runnable
# runtime) plus a Migrations module; the transform runs through the interpreter,
# so the project's OCaml runtime must be built first (clerk run warms it).
# ============================================================================
rm -rf _xform && mkdir -p _xform
cp opttup.catala_en _xform/OptTup.catala_en
printf '[project]\ninclude_dirs = ["."]\n' > _xform/clerk.toml
# OLD shape: add input rate:decimal; a test that fills it; pin + snapshot
sed -i 's/\(input pair content (integer, money)\)/\1\n  input rate content decimal/' _xform/OptTup.catala_en
sed 's/#\[testcase.sig[^]]*\]//' test_opttup.catala_en > _xform/src.catala_en
sed -i 's/\(definition calc.pair equals (7, \$3.00)\)/\1\n  definition calc.rate equals 3.5/' _xform/src.catala_en
( cd _xform && clerk start >/dev/null 2>&1 )
( cd _xform && catala testcase read src.catala_en | catala testcase write --language en --sig-dir . > t.catala_en )
# DRIFT: retype rate decimal -> money (a NeedsDecision)
sed -i 's/input rate content decimal/input rate content money/' _xform/OptTup.catala_en
# the transform: input named after the consumed field, single `result` output
cat > _xform/migrations.catala_en <<'EOF'
> Module Migrations

```catala-metadata
declaration scope Rate_v2:
  input rate content decimal
  output result content money
```

```catala
scope Rate_v2:
  definition result equals $1.00 * rate
```
EOF
( cd _xform && clerk start >/dev/null 2>&1 )
[ "$( ( cd _xform && catala testcase migrate status --json t.catala_en 2>/dev/null ) | jq -r '.[0].state' )" = "Stale" ] \
  || { echo "FAIL(xform): expected Stale after retype"; exit 1; }
cp _xform/t.catala_en _xform/t.stale.bak   # src no longer typechecks post-retype; keep the stale test
# build the OCaml runtime (.cmxs) the interpreter needs, via a warmup run
cat > _xform/warmup.catala_en <<'EOF'
> Using OptTup
> Using Migrations

```catala-metadata
#[test]
#[testcase.testui]
declaration scope Warmup:
  output t scope Migrations.Rate_v2
```

```catala
scope Warmup:
  definition t.rate equals 3.5
```
EOF
( cd _xform && clerk run warmup.catala_en >/dev/null 2>&1 ) \
  || { echo "FAIL(xform): warmup build/run failed"; exit 1; }
# plan, point the transform at the scope, apply
( cd _xform && catala testcase migrate plan -o plan.toml t.catala_en 2>/dev/null )
grep -q 'reason = "needs explicit migration: rat -> money"' _xform/plan.toml \
  || { echo "FAIL(xform): retype not listed as a transform"; cat _xform/plan.toml; exit 1; }
sed -i 's/  fn = "?"/  fn = "Migrations.Rate_v2"/' _xform/plan.toml
XF=$( cd _xform && catala testcase migrate apply --plan plan.toml t.catala_en 2>/dev/null )
echo "$XF" | grep -qi 'transformed from plan' \
  || { echo "FAIL(xform): expected 'transformed from plan'; got:"; echo "$XF"; exit 1; }
# 3.5 (decimal) became $3.50 (money), placed into the slot
grep -q 'definition calc.rate equals \$3.50' _xform/t.catala_en \
  || { echo "FAIL(xform): transform result not written ($3.50 expected)"; grep rate _xform/t.catala_en; exit 1; }
[ "$( ( cd _xform && catala testcase migrate status --json t.catala_en 2>/dev/null ) | jq -r '.[0].state' )" = "Fresh" ] \
  || { echo "FAIL(xform): transformed test is not Fresh"; exit 1; }

# a transform pointing at a non-existent scope: reported, slot left a decision (stale).
cp _xform/t.stale.bak _xform/t.catala_en   # the still-stale (decimal-pinned) test
( cd _xform && catala testcase migrate plan -o plan.toml t.catala_en 2>/dev/null )
sed -i 's/  fn = "?"/  fn = "Migrations.Does_not_exist"/' _xform/plan.toml
BADXF=$( cd _xform && catala testcase migrate apply --plan plan.toml t.catala_en 2>/dev/null )
echo "$BADXF" | grep -qi 'transform failed' \
  || { echo "FAIL(xform): bad transform fn must be reported; got:"; echo "$BADXF"; exit 1; }
echo "$BADXF" | grep -qi 'left STALE' \
  || { echo "FAIL(xform): failed transform must leave the test stale; got:"; echo "$BADXF"; exit 1; }
