(library
 (name testcase)
 (modules project model commands recovery)
 (libraries
   catala.driver
   catala.clerk_lib
   catala_types_atd
   catala.clerk_backend
   catala.clerk_utils
   re
   unix)
 (flags
  (:standard -open Catala_types_atd)))

(executable
 (name testcase_plugin)
 (modes plugin)
 (modules testcase_plugin)
 (libraries yojson atdgen-runtime testcase catala.clerk_utils)
 (embed_in_plugin_libraries
  otoml
  ninja_utils
  catala.clerk_lib
  catala.clerk_utils
  catala.clerk_backend
  atdgen-runtime
  catala_types_atd
  testcase))

(install
 (files
  (testcase_plugin.cmxs as catala/plugins/testcase.cmxs))
 (section libexec_root))
